spring.application.name=session9
#Database
spring.datasource.url= jdbc:postgresql://localhost:5432/human_resource_management
spring.datasource.username = postgres
spring.datasource.password = 1234
#JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
#DevTools
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
